Attica-org/athens-client

.eslintrc.json, package.json, src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx, src/app/(chat)/_components/organisms/ErrorBoundaryMessage.tsx, src/app/(chat)/agoras/[agora]/page.tsx, src/app/(main)/_components/organisms/SearchDeciderSuspense.tsx, src/app/_components/templates/ErrorFallback.tsx, src/lib/fetchWrapper.ts, yarn.lock
- ErrorBoundary 처리를 '아고라 목록 불러오기', '채팅 내역 불러오기' , '채팅방 인원 목록 불러오기' 페이지에 적용
- Windows 환경에서 발생하는 CRLF / LF 충돌문제 ESlint 설정을 통해 해결. 
- 잘못된 API에 요청할 시, 무한 retry 문제 일부 완화. (여전히 의도한대로 동작하지 않기에 추후 수정)
=> ErrorBoundary 처리, CRLF / LF 충돌 문제 해결 , 무한 retry 문제 일부 완화

.eslintrc.json, src/app/(main)/_components/molecules/SearchDecider.tsx, src/app/(main)/_components/organisms/SearchDeciderSuspense.tsx
- HydrationBoundary 하위에 ErrorBoundary 처리
- 렌더링 중 컴포넌트 정의를 피하기 위해 미리 컴포넌트를 정의한 뒤 사용함.
=> Fix : ErrorBoundary 래핑시 렌더링 중 컴포넌트 정의 문제 해결

src/app/(chat)/_components/atoms/ChatNotification.tsx, src/app/(chat)/_components/atoms/SocialShareLogos.tsx, src/app/(chat)/_components/molecules/AgoraTitle.tsx, src/app/(chat)/_components/molecules/MessageInput.tsx, src/app/(chat)/_components/organisms/Header.tsx, src/app/(main)/flow/enter-agora/_components/EnterAgoraButton.tsx
resolved: #35  
- 관찰자는 메타데이터 메시지를 받지 못하는 문제 해결
- 종료된 아고라의 경우 입장 시 저장한 전역 상태로 종료된 아고라인지 확인하여 웹소켓 미연결
- 종료된 아고라의 경우 찬/반 인원 미출력 (어차피 0명이기 때문)
- 데스크탑 라이트모드일 때 공유 모달의 로고 이름이 가려지는 문제 수정
- 아고라 입장시 저장하는 useAgora 전역 상태의 enterAgora.status를 사용하여 종료된 아고라인지 확인
- 종료된 아고라의 경우 찬/반 인원 미출력, 웹소켓 미연결
- 웹소켓 연결이 어떤 과정으로 이루어지는지 확인해보세요!
메타데이터: connect -> subscribeError -> subscribe (metaData)
메시지 전송: connect -> subscribeError -> subscribe (message) -> send
웹소켓에서의 에러는 `/user/queue/errors`로 전송됩니다.
모든 에러는 저 곳에서 오기 때문에 Header, MessageInput 컴포넌트 각각 subscribe하지 않고, 상위 컴포넌트인 Header에서 subscribe하도록 했습니다.
<br>
---
=> 종료된 아고라 소켓 미연결 및 필요없는 정보 미출력

src/app/(chat)/_components/molecules/DiscussionStatus.tsx, src/app/(chat)/_components/organisms/AgoraUserSide.tsx, src/app/(chat)/_components/organisms/Header.tsx, src/app/(chat)/layout.tsx, src/store/chatInfo.ts
resolved: #41
- 모바일 환경에서 채팅방 입장 후 키보드 입력시 화면이 키보드의 높이만큼 상단으로 올라가 안보이는 문제가 있었음
- 아고라 title이 투표 모달에서 보이지 않는 문제가 있었음
- 채팅방의 레이아웃에 존재하던 h-dvh를 h-full로 변경, inset-y-full 제거
- 채팅 관련 전역 상태를 소켓 연결이 끊길 때 reset하지 않고 헤더 전체 unmount시 reset하는 것으로 로직 변경
- 
<br>
---
=> 채팅방 메타데이터 버그 수정

src/app/(main)/_components/atoms/Agora.tsx, src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx, src/store/create.ts
resolved: #52
- 종료 아고라 입장시, api 요청하지 않고 바로 입장
- 아고라 생성 후 및 처음 마운트될 때 전역 상태 초기화
<br>
---
=> [#52] 종료 아고라 입장시 바로 입장, 아고라 생성 후 전역 상태 reset

src/app/(chat)/_components/molecules/DiscussionStatus.tsx, src/app/_components/molecules/ModalBase.tsx, src/lib/fetchWrapper.ts, src/lib/getReissuanceToken.ts, src/lib/getToken.ts, src/lib/retryConfig.ts
- Modal 닫힐 때 CreateAgora reset
- token은 개별 관리 하도록 수정하여 Retry 오류 해결
- 종료 투표 후, 한번 더 누르지 못하도록 disabled 설정
- goraEnd가 onSuccess로 진입할 때, state관리를 통해 disabled 설정을 해주었습니다.
<br>
---
=> Retry 오류 token 개별 관리, Modal 닫힐 때 reset 설정, [#53] 종료 투표 후, disabled 설정

src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx, src/app/(main)/_components/atoms/SearchAgora.tsx
resolved: #1 #2
- 종료된 아고라 키워드 검색 후 입장시 모달 거치지 않도록 수정
- 토론 종료시 유저 목록 보이지 않도록 수정
<br>
---
=> #[62] 토론 종료시 유저 목록 초기화, 종료된 아고라 키워드 검색 후 입장시 모달 거치지 않도록 수정

src/app/(chat)/_components/templates/EndAgora.tsx, src/app/(main)/_components/atoms/Agora.tsx, src/app/(main)/_components/molecules/AgoraList.tsx, src/app/(main)/_lib/getAgoraCategorySearch.ts, src/app/_components/utils/ServiceWorkerRegistration.tsx, src/app/model/Agora.ts, src/assets/icons/ArrowDownIcon.tsx
- service worker 상태 변화 감지하여 재등록
- 카테고리 조회에서 종료된 아고라는 참여인원이 아닌 투표 결과 데이터 출력
- service worker의 oncontrollerchange 함수를 사용하여 상태 변화 감지
- 상태 변화가 감지되면 service worekr 재등록
- 카테고리 조회 하나의 api에서 데이터가 다르게 오므로 type 가이드를 사용하여 리스트의 타입 변화를 줌
- 
<br>
---
=> service worker 상태 변화 감지 및 재등록

src/app/(chat)/_components/organisms/Header.tsx, src/app/(chat)/agoras/[agora]/layout.tsx, src/app/(main)/_components/atoms/SearchAgora.tsx, src/app/_components/utils/ServiceWorkerRegistration.tsx, src/utils/showToast.ts
- 아고라 키워드 검색 시 종료 아고라 참여인원이 아닌 투표 결과 출력
- 서비스워커 상태 'redundant'로 변경시 서비스워커 재등록 및 채팅방 입장 전 서비스워커 상태 체크
- toast ui duration 2000ms로 조정
- 채팅방에서 한쪽 입장이 1명만 남은 상태에서 모두 나가면 0으로 변경되지 않는 문제 수정
- 타입 가이드를 사용하여 종료 아고라 데이터를 서버로부터 받으면 그에 맞게 출력문 조정
- 서비스워커 및 controller에 `statechange` 이벤트를 붙여 'redundant'로 상태 변경시 재등록
- meta 메시지를 받으면 기본값으로 초기화된 participants 객체를 생성하여 이 객체에 참여인원 저장, 상태 변경
- 
<br>
---
=> QA2에서 발견한 서비스워커, 채팅방 문제

next.config.js, src/app/(chat)/_components/atoms/HamburgerButton.tsx, src/app/(chat)/_components/atoms/MyMessage.tsx, src/app/(chat)/_components/atoms/YourMessage.tsx, src/app/(chat)/_components/molecules/Message.tsx, src/app/(chat)/_components/organisms/ErrorBoundaryMessage.tsx, src/app/(chat)/_components/organisms/Header.tsx, src/app/(chat)/_components/organisms/MessageContainer.tsx, src/app/(chat)/agoras/[agora]/page.tsx, src/app/(main)/_components/atoms/CategoryAgora.tsx, src/app/(main)/_components/atoms/SearchBar.tsx, src/app/(main)/_components/molecules/AgoraListDecider.tsx, src/app/(main)/_components/molecules/CategoryAgoraList.tsx, src/app/(main)/_components/molecules/CategoryButtonList.tsx, src/app/(main)/_components/molecules/KeywordAgoraList.tsx, src/app/(main)/_components/organisms/AgoraListDeciderHydration.tsx, src/app/(main)/_components/templates/Main.tsx, src/app/(main)/create-agora/_component/AgoraTitleInput.tsx, src/app/_components/utils/DefferedComponent.tsx
- 홈 화면에서 카테고리 클릭마다 페이지 전체 리렌더링 문제 해결
- 키워드 검색 시마다 페이지 전체 리렌더링 문제 해결
- 채팅방 유저 리스트 meta type 소켓 응답 받을 때마다 호출 수정
- 채팅방 전송 시간 카톡처럼 마지막 전송 시간만 보이도록 수정
- 서버 컴포넌트에서 prefetch한 데이터 사용하도록 수정
- fetch 중일 때마다 로더가 보이는 것이 아닌, 일정 시간이 지난 후 보이도록 수정하여 UX 향상 도모
- shallow routing을 사용하여 url만 변경되고 화면은 리렌더링이 되지 않도록 한다.
- shallow routing으로 url이 변경되면, 이를 useSearchParam은 감지하지 못하기 때문에 상태 변화를 줄 수 없게 된다. 그렇기에 전역 상태를 사용하여 직접 상태를 감지하여 필요한 부분만 리렌더링이 진행되도록 수정하였다.
- 홈에서 서버컴포넌트에서 미리 데이터를 prefetch하여 아고라 리스트를 불러준다. 해당 데이터를 react query의 InitialData property에 추가해주어 초기 렌더링 시 서버 컴포넌트에서 호출한 데이터를 보여주도록 하였다.
- 데이터 fetch 때마다 로더가 보이도록 한다면, 빠른 시간 안에 서버로부터 데이터를 받게 될 때 사용자는 로더나 스켈레톤으로 인해 화면이 깜빡이는 것 같은 느낌을 받을 수 있다. 이러한 현상을 줄이기 위해 일정 시간이 지난 후에만 로더가 출력되도록 DefferedComponent를 추가해주었다.
- shallow routing에 대해 이해하고 이를 적용하기 위해 어떻게 코드를 수정했는지 봐주세요 …
=> 홈, 채팅 화면 리렌더링 최적화

src/app/(chat)/_components/organisms/MessageContainer.tsx, src/app/(main)/_components/atoms/CategoryAgora.tsx, src/app/(main)/_components/atoms/ClosedAgoraVoteResultBar.tsx, src/app/(main)/_components/atoms/KeywordAgora.tsx, src/app/(main)/_components/molecules/AgoraListDecider.tsx, src/app/(main)/_components/molecules/CategoryAgoraList.tsx, src/app/(main)/_components/molecules/LivelyAgoraList.tsx, src/app/(main)/_components/organisms/AgoraListDeciderHydration.tsx, src/app/(main)/_components/templates/Main.tsx, src/app/(main)/_lib/getLivelyAgora.ts, src/app/_components/molecules/AgoraImageUpload.tsx, src/app/model/Agora.ts
- 종료된 아고라 투표 결과 텍스트가 아닌 그래프로 표현
- 인기 아고라 swiper로 구현
- 그래프는 너비의 퍼센트(%)를 사용하여 찬/반 표현하였습니다.
- 인기 아고라 페이지가 `shallow routing`을 사용하고 있어 dom unmount가 되지 않아 swiper가 처음 새로고침시에만 동작합니다.
이는 swiper가 적용될 태그에 key 값을 주고 다른 페이지에서 넘어오는 등의 dom unmount 및 update가 필요할 땐 key 값을 다르게 주어 강제 리렌더링을 시켜주도록 하여 해결하였습니다.
<br>
---
=> 종료 아고라 그래프 표현, 인기 아고라 구현

src/app/(chat)/_components/molecules/Message.tsx
- 채팅방 message.length로 메시지 존재 여부 확인하던 것을 비교 연산자 추가함
- 
- 
<br>
---
=> fix: 채팅방에서 messages.length 출력되는 문제 수정

public/custom-sw.js, src/app/(chat)/_components/organisms/Header.tsx, src/app/(chat)/_components/templates/EndAgora.tsx, src/app/(chat)/_lib/getAgoraUsers.ts, src/app/(chat)/_lib/getChatMessages.ts, src/app/(chat)/_lib/getVoteResult.ts, src/app/(chat)/_lib/patchAgoraEnd.ts, src/app/(chat)/_lib/patchAgoraImg.ts, src/app/(chat)/_lib/patchAgoraStart.ts, src/app/(chat)/_lib/patchAgoraTimeOut.ts, src/app/(chat)/_lib/patchChatExit.ts, src/app/(chat)/_lib/postFilterBadWords.ts, src/app/(chat)/agoras/[agora]/page.tsx, src/app/(main)/_components/organisms/EnterAgoraContent.tsx, src/app/(main)/_lib/getAgoraTitle.ts, src/app/(main)/_lib/postCreateAgora.ts, src/app/(main)/_lib/postEnterAgoraInfo.ts, src/app/(main)/flow/enter-agora/_components/EnterAgoraButton.tsx, src/app/config/RQProvider.tsx, src/auth.config.ts, src/hooks/useApiError.ts, src/hooks/useUpdateSession.ts, src/hooks/useVote.tsx, src/lib/fetchWrapper.ts, src/lib/getReissuanceToken.ts, src/middleware.ts, src/serverActions/auth.ts, src/utils/isNull.ts
-  #104  
- 콘솔 제거
- 서비스워커 인증 로직 변경
- indexedDB 사용 코드 제거
- 토큰 재발급 훅 구현
- 모달에서 토큰 재발급 코드 호출시 404 페이지로 이동하는 문제는 클라이언트 파일에서 서버 코드를 호출하려고 하여 발생한 문제였습니다.
- 에러 핸들링 파일은 클라이언트이므로, 토큰 재발급 코드를 훅을 통해 실행되도록 하여 서버 호출로 인한 문제를 해결하였습니다.
- 만약 클라이언트 파일에서 reissue를 호출하고자 한다면, `useUpdateSession`의 `callReissueFn` 함수를 사용하세요.
- 
<br>
---
=> 클라이언트에서 서버 코드 호출로 인한 버그 수정

public/custom-sw.js, src/app/(chat)/_lib/getAgoraUsers.ts, src/app/(chat)/_lib/getChatMessages.ts, src/app/(chat)/_lib/getVoteResult.ts, src/app/(chat)/_lib/patchAgoraEnd.ts, src/app/(chat)/_lib/patchAgoraImg.ts, src/app/(chat)/_lib/patchAgoraStart.ts, src/app/(chat)/_lib/patchAgoraTimeOut.ts, src/app/(chat)/_lib/patchChatExit.ts, src/app/(chat)/_lib/postFilterBadWords.ts, src/app/(main)/_lib/getAgoraCategorySearch.ts, src/app/(main)/_lib/getAgoraKeywordSearch.ts, src/app/(main)/_lib/getAgoraTitle.ts, src/app/(main)/_lib/getLivelyAgora.ts, src/app/(main)/_lib/postCreateAgora.ts, src/app/(main)/_lib/postEnterAgoraInfo.ts, src/app/(main)/page.tsx, src/app/(main)/user-info/_component/molecules/ActionButtons.tsx, src/app/(main)/user-info/_component/organisms/UserInfoMain.tsx, src/app/(main)/user-info/page.tsx, src/constants/responseErrorMessage.ts, src/middleware.ts
resolved: 
- 서비스워커에서 제공하는 캐싱 기능을 사용하여 정적/동적 코드에 대해 캐싱 적용
- 오프라인시 캐싱된 데이터 사용
- 오프라인에서 API 요청시 인터넷 연결 확인 요청 응답 반환
- `user-info` 페이지의 `Main` 컴포넌트와 홈 화면의 `Main` 컴포넌트와 충돌이 발생해 로그아웃 후 홈 화면 컴포넌트가 출력되는 문제가 발생하였습니다.
- `user-info` 페이지의 `Main` 컴포넌트의 이름을 `UserInfoMain`으로 변경하여 해결하였습니다.
- 페이지에 접속한 적이 있다면 서비스워커에 캐시합니다.
- 이전에 접속한 적이 있다면, 캐시한 데이터를 사용자에게 반환합니다. (UI, data)
- API 요청의 경우 캐시 데이터가 아닌 실시간 데이터를 반환하고, 이를 항상 캐시하도록 합니다.
- 캐시 용량 제어를 위해 같은 API 요청일 경우 해당 캐시를 갱신하도록 합니다.
- 오프라인에서의 API 응답 코드는 `503`으로 지정했습니다.
- 이에 따른 메시지는 `'인터넷 연결이 필요합니다. 다시 시도해주세요.'`입니다.
- `responseErrorMessage.ts` 파일에 추가했으니 혹 사용하고자 한다면, import 하여 사용해주세요.
<br>
---
- **선택 반영**: 반영해도 좋고 넘어가도 좋습니다. 그냥 …
=> 서비스워커 캐싱 적용 및 오프라인 API 응답 반환

src/app/(chat)/_components/atoms/ChatNotification.tsx, src/app/(chat)/_components/atoms/NotificationNewMessage.tsx, src/app/(chat)/_components/atoms/ScrollToBottomBtn.tsx, src/app/(chat)/_components/molecules/Message.tsx, src/app/(chat)/_components/organisms/Header.tsx, src/app/(chat)/_lib/getChatMessages.ts, src/app/(chat)/_lib/getChatMessagesServer.ts, src/app/(chat)/agoras/[agora]/page.tsx, src/app/(main)/_components/atoms/AgoraStatusTab.tsx, src/app/(main)/_components/atoms/CategoryAgoraNowTitle.tsx, src/app/(main)/_components/organisms/CategoryButtonContainer.tsx, src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx, src/app/(main)/login/auth/components/AuthLogin.tsx, src/app/_components/organisms/AgoraImageUpload.tsx, src/constants/queryKey.ts, src/utils/swalAlert.ts, tailwind.config.ts
- `useInView`를 사용하던 가상스크롤 로직을 제거하고 wheel 이벤트를 사용하여 새로운 데이터를 불러오도록 수정
- 홈의 URL searchParams가 탭 변경시 이전 데이터로 출력되는 버그 수정
- 가상스크롤은 채팅 리스트 컴포넌트를 scaleY(-1)로 뒤집은 뒤(스크롤), 메시지 컴포넌트를 다시 scaleY(-1)로 돌려줘 마우스 휠 로직이 반대로 동작하도록 했습니다.
- 이에 wheel 이벤트를 추가하여 기존 마우스 동작대로 스크롤을 움직여도 정상 작동하도록 하였습니다.
- 
<br>
---
=> 가상스크롤 로직 변경 및 홈 버그 수정

src/app/(chat)/_components/organisms/Header.tsx, src/app/(main)/_components/atoms/CategoryAgora.tsx, src/app/(main)/_components/atoms/KeywordAgora.tsx, src/app/(main)/_components/atoms/NoAgoraMessage.tsx, src/app/(main)/_components/molecules/CategoryAgoraList.tsx, src/app/(main)/_components/molecules/LivelyAgoraList.tsx, src/app/(main)/_components/templates/Main.tsx, src/app/(main)/_components/templates/SignIn.tsx, src/app/(main)/_lib/getEnterClosedAgoraStatus.ts, src/app/(main)/_lib/postEnterAgoraInfo.ts, src/app/_components/atoms/loading.tsx, src/app/_components/molecules/SNSLogin.tsx, src/auth.config.ts, src/constants/queryKey.ts, src/constants/responseErrorMessage.ts
- 로그인 페이지에 비회원으로 불러오기 Link 추가
- 종료된 아고라 접근시 인증 로직 실행
- 
- 홈에서 인기 아고라, 활성화 아고라 로더의 크기가 달라서 통일시켜주었습니다.
<br>
---
=> 종료된 아고라에 유저 인증 로직 추가

src/app/(chat)/_components/organisms/Header.tsx, src/app/(main)/_components/atoms/CategoryAgoraNowTitle.tsx, src/app/(main)/_components/molecules/AgoraListDecider.tsx, src/app/(main)/_components/molecules/CategoryAgoraList.tsx, src/app/(main)/create-agora/_component/CreateAgoraBtn.tsx
- '전체' 카테고리가 아닌 그 외 카테고리에서의 새로고침 버튼이 동작하지 않는 문제 수정
- 전역 상태로 관리하던 category, tabStatus를 불러와 query에 적용
- 
<br>
---
=> 카테고리별 새로고침 작동 안되는 문제 수정

src/app/(chat)/_components/atoms/ChatPageLoading.tsx, src/app/(chat)/_components/molecules/Message.tsx, src/app/(chat)/_components/organisms/Header.tsx, src/app/(chat)/layout.tsx, src/app/(main)/_components/atoms/CategoryAgoraNowTitle.tsx, src/app/(main)/_components/molecules/AgoraListDecider.tsx, src/app/(main)/_components/molecules/CategoryAgoraList.tsx, src/app/(main)/_lib/postEnterAgoraInfo.ts, src/app/config/ChatPageLoadConfig.tsx, src/constants/responseErrorMessage.ts, src/hooks/useUnloadDisconnectSocket.tsx, src/store/agora.ts, src/store/enter.ts
- 채팅방 입장하기 API 호출 후 종료된 아고라일 시 종료된 아고라라는 알림 리턴하도록 수정
- 채팅방 새로고침시 기존 프로필 유지하도록 개선
- `performance.getEntriesByType`을 사용하여 새로고침인지, 다른 페이지에서 이동한 것인지 판별하여 새로고침을 인식하도록 했습니다.
- zustand 전역 상태로 관리 중이던 유저 프로필 정보를 `persist`로 `sessionStorage`에 저장하여 새로고침 후에도 데이터를 유지하도록 수정하였습니다.
- storage는 클라이언트 사이드에서만 사용할 수 있으므로, 세션과 유저 정보를 불러오는 서버 사이드 렌더링 시간 동안은 채팅방의 빈 레이아웃을 보여주도록 하였습니다.
- 
- [페이지 새로고침 여부 확인 방법](https://seeminglyjs.tistory.com/490)
<br>
---
=> 채팅방 새로고침 시 프로필 유지하도록 개선

src/app/_components/utils/SetTheme.tsx, src/app/layout.tsx
- 테마 스위치 버튼을 누를 때만 meta 태그가 추가되던 것을 첫 렌더링 후 바로 추가되도록 수정
- setTheme에 테마 값 설정할 때 같이 설정해주도록 하였습니다.
- 
<br>
---
=> 첫 렌더링 후 meta로 테마 설정 추가

src/app/(chat)/_components/atoms/ChatPageLoading.tsx, src/app/(chat)/_components/atoms/HamburgerButton.tsx, src/app/(chat)/_components/atoms/ShareButton.tsx, src/app/(chat)/_components/molecules/MenuItems.tsx, src/app/(chat)/_components/organisms/Header.tsx, src/app/(main)/_components/atoms/CategoryAgora.tsx, src/app/(main)/_components/atoms/KeywordAgora.tsx, src/app/(main)/_lib/getAgoraTitle.ts, src/app/(main)/login/route.ts, src/app/(main)/page.tsx, src/app/(main)/user-info/_lib/postLogout.ts, src/app/_components/utils/SessionNavigationObserver.tsx, src/app/_components/utils/SetChatInfoReset.tsx, src/app/config/ChatPageLoadConfig.tsx, src/app/layout.tsx, src/app/model/Agora.ts, src/constants/segmentKey.ts, src/hooks/useApiError.ts, src/hooks/usePreviousPage.ts, src/hooks/useUnloadDisconnectSocket.tsx, src/hooks/useUpdateSession.ts, src/store/agora.ts
- 채팅방에서 다른 채팅방으로 넘어갈 때(navigate)
- ACTIVE AGORA일 땐 `/flow` 입장하기 모달 출력
- CLOSED AGORA일 땐 종료된 아고라라는 `showToast` 띄우기
- 같은 채팅방일 때(reload)
- 기존 아고라가 ACTIVE라면 재입장 API 호출
- redirect는 상대 경로가 아닌 절대 경로를 사용해야 하므로 env 환경 파일에서 불러온 origin 추가
- 종료된 아고라에서 뒤로가 홈으로 이동시 다시 채팅방으로 이동하면서 에러가 발생하는 문제 수정
- reload 감지시 라우터 이동에서 서버로부터 새로운 데이터를 불러올 때도 reload로 감지하는 문제로 인해 세션 스토리지에 이전/현재 URL을 저장하여 reload 감지하도록 조건문 추가
- 종료된 아고라에서 새로고침시 unload에서 아고라 전역 상태 초기화되지 않도록 하여 기존 데이터 유지하도록 수정
- 종료된 아고라 입장 API 호출 조건을 전역 상태를 기반으로 했던 것을 버튼 클릭을 감지하여 호출하도록 수정
- 
<br>
---
=> 종료/활성화 채팅방에서의 새로고침 시 자동 재입장 되도록 로직 수정

src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx, src/app/(chat)/_components/organisms/Header.tsx, src/app/(chat)/_lib/getAgoraUsers.ts, src/app/(main)/_components/atoms/CategoryAgora.tsx, src/app/(main)/_components/atoms/KeywordAgora.tsx, src/app/(main)/_lib/postEnterClosedAgora.ts, src/app/model/Agora.ts
- 채팅방에서 라우터 이동시 페이지 이탈 방지 모달이 뜨는 문제 수정
- 종료된 아고라 입장시 GET 요청 보내던 API POST로 수정
- 채팅방 이미지 수정되었을 때, 채팅방 내 유저들에게 이미지 수정사항이 적용되지 않는 문제 수정
- 세션 쿠키에 저장해두었던 '현재 URL', '이전 URL'을 활용해서 페이지 이탈 방지 모달이 뜨지 않도록 했습니다.
- 채팅방에서 라우터로 인한 경로 변경시 현재 경로와 이전 경로를 채팅방 URL (/agoras/${agoraId})로 같게 하여 페이지 이동으로 감지하지 않도록 하였습니다.
- 종료된 아고라 입장 API가 GET에서 POST로 바뀌면서, useQuery로 관리해주던 데이터를 useMutation으로 수정해주었습니다.
- 사이드바 API 호출 시 유저 리스트만 응답받던 API에 thumbnail까지 추가하여 이미지가 수정되었을 시 적용될 수 있도록 하였습니다.
- .
<br>
---
=> QA에서 발견된 버그 수정사항 적용

src/app/(chat)/_components/molecules/AgoraUserList.tsx, src/app/(chat)/_components/molecules/Message.tsx, src/app/(chat)/_lib/postKickVote.ts
- 강제퇴장 투표시 성공여부 Toast에 띄우는 기능 추가
- 강퇴 투표를 자신에게 할 수 없도록 수정
- 기존 채팅에 반응을 남겨도 제대로 표시되지 않던 문제 해결
- 채팅 반응 로직을 api를 통해 받아온 기존 반응을 기준으로 카운트 하도록 변경
<br>
---
=> 강제 퇴장 동작 및 채팅 반응 로직 수정

.yarnrc.yml, src/app/(main)/_lib/postCreateAgora.ts, src/app/(main)/create-agora/_component/CreateAgoraImageUpload.tsx, src/app/_components/molecules/ImageCropper.tsx, src/utils/convertBase64ToBlobUrl.ts, src/utils/getCroppedImg.ts
- 크롭한 이미지 png에서 jpeg로 저장하도록 변경
- 아고라 생성 후 입장 모달 뜰 때 세션 쿠키에 데이터 url이 아닌 blob url로 저장하도록 수정
- 개발 기능에 작성된 방법으로 수정하였습니다.
- 
<br>
---
=> 아고라 생성시 크롭 이미지 크기로 세션 용량 초과 문제 수정

src/app/(chat)/_components/molecules/AgoraUserList.tsx, src/app/(chat)/_components/molecules/Message.tsx, src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx, src/app/_components/utils/SetChatInfoReset.tsx, src/utils/swalAlert.ts
- 채팅방에서 강퇴된 인원이 이후 강퇴 투표의 과반수 계산에 포함되는 문제를 수정
- 계정 삭제시 progress bar 안내 메시지 변경
- 몇 몇 리팩토링
- 현재 아고라에 참여하고 있는 유저를 {id: 닉네임} 형태로 participants(Map 객체)에 저장하고 쓰고 있는데, 다른 유저가 강퇴 되었을 때 해당 인원을 participants에서 제거해줌으로써, 총 인원수를 관리하도록 변경했습니다.
<br>
---
=> 채팅방에서 강퇴된 인원이 이후 강퇴 투표의 과반수 계산에 포함되는 문제를 수정

src/app/(main)/_lib/postCreateAgora.ts
- 기존에 이미지 없이 채팅방 생성할 때 file을 빈 문자열('')로 넘겨주면 되었지만, 서버 코드 수정으로 인해 File 객체로 넘겨줘야 하는 문제로 인해 빈 문자열을 File 객체로 전달하도록 수정
- 개발 기능과 동일합니다.
- 
<br>
---
=> 이미지 없이 채팅방 생성시 파일 형태로 전달하지 않으면 발생하는 에러 수정

src/app/(chat)/_components/molecules/ModifyAgoraImage.tsx, src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx, src/app/(chat)/_components/templates/AgoraSideBar.tsx, src/app/(chat)/utils/resetStateOnChatExit.ts, src/app/config/ChatPageLoadConfig.tsx, src/app/model/Agora.ts, src/store/agora.ts, src/utils/validation/validateImage.ts
- 채팅방 뒤로가기 시 가끔 입장하기 모달이 뜨는 문제
- 채팅방 사이드가 열 때 채팅방 이미지가 안보이는 문제
- 뒤로가기 시 호출되는 reset 모음 함수에서 selectedAgora reset을 제외하여 호출하도록 수정
- 남아있는 채팅방 정보가 없어서 상위 컴포넌트인 `ChatPageLoadConfig` 파일에서 다른 페이지에서의 접근으로 인식해 입장 모달을 띄운 것입니다.
- 그래서 selectedAgora 정보를 남겨주도록 하였습니다.
- selectedAgora 정보를 가지고 채팅방 직접 접근시의 유저 시나리오는 이전에 고려해두었습니다.
- 채팅방에서 아고라 이미지가 가끔 보이지 않는 문제는, 서버로부터 응답받은 이미지 프로퍼티가 클라이언트에 저장된 타입 정보와 일치하지 않아 발생한 것입니다.
이를 같게 해주었습니다.
<br>
---
=> 채팅방 뒤로가기 문제 및 서버 응답 이미지 프로퍼티 key 수정

src/app/(chat)/_components/atoms/UserAccessNotification.tsx, src/app/(chat)/_components/molecules/AgoraUserList.tsx, src/app/(chat)/_components/organisms/Header.tsx, src/app/(chat)/utils/resetStateOnChatExit.ts, src/app/(chat)/utils/updateUserAccessMessage.tsx, src/app/_components/utils/SetChatInfoReset.tsx, src/app/model/AccessStatus.ts, src/app/model/Agora.ts, src/app/model/Message.ts, src/store/kickedUser.ts
- 채팅방 유저 강퇴시 다른 사용자들에게 강퇴 메시지 가도록 구현
- 강퇴 당한 사용자 목록이 렌더링에 영향을 주지 않기에, 전역 상태가 아닌 싱글턴 패턴을 사용해 전역에서 접근 가능한 객체를 만들었습니다.
- 유저가 퇴장할 때 모두에게 전송되는 메타 정보를 처리할 때, 강퇴 당한 사용자 목록에 해당 유저가 존재할 경우, 해당 유저가 강제퇴장 당했음을 알리도록 하는 메시지를 띄우도록 했습니다.
<br>
---
=> 채팅방 유저 강퇴시 다른 사용자들에게 강퇴 메시지 가도록 구현
