- LICENSE
> docs: LICENSE 추가

- src/app/(chat)/_lib/getAgoraUsers.ts
- src/app/(chat)/_lib/getChatMessages.ts
- src/app/(main)/_lib/getAgoraCategorySearch.ts
- src/app/(main)/_lib/getAgoraKeywordSearch.ts
- src/lib/fetchWrapper.ts
- #23 
- 무한 재시도 수정
- 재시도 횟수 초과시 에러 응답 작성
- custom error 추가
- 아고라 카테고리 검색, 아고라 키워 검색, 채팅 사용자 조회, 채팅 내역 조회 커스텀 에러 처리
> [#23] Issue 처리

- src/lib/fetchWrapper.ts
- retry 3회 초과시 이후 API 요청이 안되는 것 수정
> Fix: retry 3회 초과시 이후 API 요청이 안되는 것 수정

- src/lib/getReissuanceToken.ts
> Fix: merge 충돌 해결을 위한 commit

- src/app/(chat)/_components/organisms/Header.tsx
- src/app/(chat)/_lib/getAgoraUsers.ts
- src/app/(chat)/_lib/getChatMessages.ts
- src/app/(chat)/_lib/getVoteResult.ts
- src/app/(chat)/_lib/patchAgoraEnd.ts
- src/app/(chat)/_lib/patchAgoraStart.ts
- src/app/(chat)/_lib/patchAgoraTimeOut.ts
- src/app/(main)/_lib/getAgoraTitle.ts
- src/app/(main)/_lib/postCreateAgora.ts
- src/app/(main)/_lib/postEnterAgoraInfo.ts
- src/lib/fetchWrapper.ts
- src/lib/getReissuanceToken.ts
- src/lib/getToken.ts
- src/lib/retryConfig.ts
resolved: #40 
- 토큰 재발급 함수 retry문제 해결
- 토크 발급 함수 retry 문제 해결
- retryConfig에서 retry 횟수를 전역으로 관리하도록 하고, 해당 retry를 컨트롤하여 무한 반복이 되지 않도록 수정했습니다.
<br>
---
> [#40] Fix: 토큰 재발급, 발급 함수 api retry 문제 해결

- src/app/(chat)/_components/organisms/AgoraUserSide.tsx
- src/app/(chat)/layout.tsx
- 채팅 페이지 자판 출력시 레이아웃 변경 이슈
<br>
---
> 채팅 레이아웃 변경 이슈

- src/app/(chat)/layout.tsx
> design: 키보드로 화면 밀림 현상 테스트

- src/app/(chat)/agoras/[agora]/page.tsx
- src/app/(chat)/layout.tsx
> Fix : 채팅 헤더 밀림 현상 수정

- src/app/(chat)/agoras/[agora]/page.tsx
- src/app/(chat)/layout.tsx
- 모바일 자판에 의한 화면 밀림 현상 수정 테스트
- 
- 
<br>
---
> design: 채팅 자판에 의한 화면 밀림 수정 테스트

- src/app/(chat)/agoras/[agora]/page.tsx
- src/app/(chat)/layout.tsx
> design: fixed sticky로 되돌림

- src/app/(chat)/_components/molecules/MessageInput.tsx
- src/app/(chat)/_components/organisms/Header.tsx
- src/app/(chat)/layout.tsx
- 웹소켓 에러 발생 시 toast 미출력
<br>
---
> fix: 소켓 에러 발생 시 toast 미출력

- src/app/(chat)/_components/atoms/SocialShareLogos.tsx
- src/app/(chat)/_components/molecules/ShareButton.tsx
- src/app/(chat)/_components/templates/SocialShare.tsx
- src/app/(main)/_components/atoms/NoAgoraMessage.tsx
- src/app/(main)/_components/templates/Main.tsx
- 카카오 Title undefined 출력 수정
- 디바이스 공유 기능이 아닌 제작한 공유 모달로 출력
- 
- 
<br>
---
> 채팅방 요구사항 및 버그 일부 수정

- public/custom-sw.js
- src/app/(chat)/_components/organisms/Header.tsx
- src/app/(chat)/_components/templates/EndAgora.tsx
- src/app/_components/utils/ServiceWorkerRegistration.tsx
- src/app/_components/utils/indexedDB.ts
- src/hooks/useVote.tsx
- src/utils/SWManager.ts
- tsconfig.json
- service worker는 도메인당 하나만 등록되며, 탭간에 데이터가 공유된다.
- 투표 15초의 시작 시간이 투론 종료 기준이 아닌 투표 모달이 열린 시간을 기준으로 15초여서 사용자간 투표 시간이 동기화되지 않았다.
- brower의 indexedDB를 사용하여 tabId를 저장하고, service worker와 DB가 통신하며 저장한 tabId를 사용하여 메모리에 저장된 tabId와 DB의 tabId가 일치할 때만 데이터를 갱신시킨다.
- 투표 모달이 열린 시간을 기준으로 두지 말고 토론이 종료된 시간에 15초 후를 투표 종료 시간으로 둔 후, 이를 기준으로 현재 시간과의 차이를 출력한다.
- localStorage는 동기적으로 동작하지만, indexedDB는 비동기적으로 동작합니다.
- service worker에선 localStorage 및 sessionStorage에 접근할 수 없으며, indexedDB만 접근할 수 있습니다.
- 브라우저 스토리지에 대해 알아보시면 좋을 것 같아요!
- [indexedDB 사용법](https://mong-blog.tistory.com/entry/indexedDB%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90)
<br />
service worker는 commonJS를 사용하는데, indexedDB 파일과 다른 파일들은 ESM을 사용합니다.
모듈 사용법이 달라 import/export 방식을 서로 다르게 적용해야 합니다.
indexedDB 파일을 service worker에서만 사용한다면 …
> 투표 시간 비동기화 문제 및 탭 간 데이터 공유 문제 수정

- src/app/(chat)/_components/molecules/DiscussionStatus.tsx
- src/app/(chat)/_components/organisms/Header.tsx
- src/app/(chat)/_components/templates/EndAgora.tsx
- src/app/_components/molecules/ModalBase.tsx
- success toast ui 커스텀 toast 사용
- 투표 타이머 시작 시간 및 종료 시간 동기화
- differenceInSeconds을 사용하지 않고 Date의 getTime 메서드로 투표 종료시간까지의 남은 시간 계산으로 수정
<br>
---
> toast ui 커스텀

- src/lib/fetchWrapper.ts
resolved: #1 #2
- 토큰 재발급시, 재발급된 토큰이 헤더에 제대로 반영되지 않는 문제점을 해결함.
- 함수로 보낸 헤더가, 바뀌지 않고 고정되어 있기 때문에, 재발급된 토큰이 헤더에 반영이 되지 않음을 파악했음. 이 때문에, 헤더의 내용을 재구성하고 api를 재호출 하는 작업을 통해 해결함.
<br>
---
> [#62] Fix: 토큰 재발급 토큰 미저장 문제 해결

- src/app/(chat)/_components/organisms/AgoraUserSuspense.tsx
- src/app/(chat)/_components/organisms/Header.tsx
- src/app/(chat)/_lib/getAgoraUsers.ts
- src/app/(main)/_components/atoms/ControlNumberInput.tsx
- src/app/(main)/_components/molecules/AgoraListDecider.tsx
- src/app/(main)/_components/molecules/AgoraStatusTabSuspense.tsx
- src/app/(main)/_components/molecules/CategoryAgoraList.tsx
- src/app/(main)/_components/molecules/CategoryButtonList.tsx
- src/app/(main)/_components/molecules/DiscussionDurationSetter.tsx
- src/app/(main)/_components/molecules/KeywordAgoraList.tsx
- src/app/(main)/_components/molecules/ParticipantCapacitySetter.tsx
- src/app/(main)/_components/molecules/SelectAgoraColor.tsx
- src/app/(main)/_components/organisms/AgoraListDeciderSuspense.tsx
- src/app/(main)/_components/organisms/CategoryButtonContainer.tsx
- src/app/(main)/_components/organisms/EnterAgoraContent.tsx
- src/app/(main)/_components/templates/Main.tsx
- src/app/(main)/create-agora/page.tsx
- src/app/(main)/flow/enter-agora/_components/EnterAgoraButton.tsx
- src/app/(main)/home/layout.tsx
- src/app/(main)/home/page.tsx
- src/app/_components/utils/ServiceWorkerRegistration.tsx
- src/app/model/Agora.ts
- src/app/model/AgoraUser.ts
- src/constants/agoraCategory.ts
- src/utils/tokenManager.ts
- 파일 이름 및 함수 이름 직관적으로 변경
- 무의미한 React.memo 제거
- 2회 이상 반복되는 타입 추출하여 사용
- indexedDB에 저장하는 tabId 투표하기 페이지로 넘어가지 않으면 사라지지 않는 문제 수정
indexedDB에 저장하는 tabId 투표하기 페이지로 넘어가지 않으면 사라지지 않는 문제
- Header 컴포넌트에서 tabId를 생성하여 SWManager 파일로 전역 관리한다.
- 이를 unMount되는 시점에 tabId를 clear 해준 후, indexedDB에도 제거해준다.
- 
<br>
---
> refactor: 메인 페이지 atoms 폴더 제외한 컴포넌트 파일 리팩토링

- src/app/(main)/_lib/postEnterAgoraInfo.ts
- src/app/model/Agora.ts
resolved: #1 #2
- 중복되는 타입 통합
<br>
---
> [#66] Refactor : 중복되는 타입 통합

- src/app/(chat)/_components/atoms/DiscussionTimer.tsx
- src/app/(chat)/_components/atoms/SocialShareLogos.tsx
- src/app/(chat)/_components/atoms/VoteResult.tsx
- src/app/(chat)/_components/molecules/AgoraInfo.tsx
- src/app/(chat)/_components/molecules/AgoraUserList.tsx
- src/app/(chat)/_components/molecules/DiscussionStatus.tsx
- src/app/(chat)/_components/molecules/Message.tsx
- src/app/(chat)/_components/molecules/MessageInput.tsx
- src/app/(chat)/_components/organisms/Header.tsx
- src/app/(main)/_components/atoms/CategoryAgora.tsx
- src/app/globals.css
- 중복 사용하는 전역 store 하나로 합치기
- 변수, 함수, 파일 이름 직관적이게 변경
- 중복되는 코드 컴포넌트로 추출 사용
- 아고라 COLOR 파일 분리 시 적용 안됨 문제
> 아고라 COLOR 파일 분리 시 적용 안됨 문제
- 동적 css 적용 시 css 우선순위가 뒤로 밀리면서 적용되지 않았다.
- global.css에 아고라 색상에 대한 css를 추가로 작성하여 !important로 우선순위를 높여주었다.
- global.css에만 작성하여 아고라 색상을 적용할 수 있습니다. 그렇게 되면 css 작성 시 자동완성 기능이 적용되지 않기에 tailwind 설정 파일에도 추가로 작성해주어야 합니다.
- global.css, tailwind 설정 두 파일에 아고라 색상에 대한 css를 적용해주어야 하기 때문에 기존보다 작업이 추가되게 되었습니다.
- 우선순위를 높이기 위한 또 다른 방법이 있을까요?
<br>
---
> Chat atoms, molecules 리팩토링

- src/app/(chat)/_components/organisms/Header.tsx
- src/app/(chat)/_components/templates/EndAgora.tsx
- 불필요한 함수를 제거하였습니다.
- 긴 코드를 함수화하여 가독성을 향상시켰습니다.
- 불필요한 메소드를 제거했습니다.(refetch)
<br>
---
> [#66] 리팩토링

- package.json
- src/app/(main)/_components/atoms/VirtuosoGridCustomList.tsx
- src/app/(main)/_components/molecules/CategoryAgoraList.tsx
- src/app/(main)/_components/templates/Main.tsx
- yarn.lock
- 충돌로 인한 메인 화면 가상 스크롤 파일 합치기 
- 
- 
<br>
---
> [#66] fix: 충돌로 인한 파일 합치기

- package.json
- public/mockServiceWorker.js
- src/app/(main)/_components/molecules/AgoraListDecider.tsx
- yarn.lock
- 
resolved: 
- 
- `.yarn`과 `package.json`에서의 typescript 버전 차이로 인한 에러
- typescript 버전을 `.yarn`에서의 버전으로 맞춰 두 파일의 버전을 동기화해줌
- 
<br>
---
> fix: 버전 충돌로 인한 에러 해결

- README.md
> Chore : 리드미 작성

- src/app/_components/_lib/OAuthRequest.ts
> fix: 배포시 발생한 async await 오류 수정

- src/app/(chat)/_components/organisms/Header.tsx
- 종료된 아고라 exit api 호출 안하도록 변경
- 종료된 상태 확인 후, exit api 호출할지 결정
<br>
---
> Fix : 종료된 아고라 exit api 호출 안하도록 변경

- src/app/(main)/login/auth/components/AuthLogin.tsx
- src/app/(main)/login/auth/page.tsx
- src/auth.config.ts
- src/middleware.ts
- secret not define auth 에러 발생
- 로그인 로딩 컴포넌트 분리
- 미들웨어 인증 확인 경로처리 추가
- env 환경 설정의 NEXTAUTH_SECRET 키 AUTH_SECRET으로 변경
- 
<br>
---
> vercel 배포 환경 auth 에러

- src/app/(chat)/_components/molecules/Message.tsx
- src/app/(chat)/_components/molecules/MessageInput.tsx
- src/app/(main)/_components/molecules/CategoryAgoraList.tsx
- 채팅을 보낼 때마다 웹 소켓 재연결 되던 문제 해결
- 가상 스크롤 문제 해결
- 다크모드에서 복사 붙여넣기시 HTML element가 삽입되는 현상 수정
- 
- 의존성 배열 수정
- endReached 속성 사용
- onPaste 속성을 통해 복사 붙여넣기 control
<br>
---
> 몇 가지 문제 해결

- src/app/robots.ts
- src/serverActions/auth.ts
resolved: 
- 소셜 로그인 메서드 POST에서 GET으로 변경됨으로 발생한 500에러 수정
- 
-
<br>
---
> 소셜 로그인 메서드 POST에서 GET으로 변경

- src/app/(chat)/_components/organisms/Header.tsx
- src/app/(chat)/utils/ServiceWorkerErrorHandler.ts
- src/app/(chat)/utils/SocketErrorHandler.ts
- src/hooks/useApiError.ts
- src/serverActions/auth.ts
- signOut에 redirect 속성 추가
<br>
---
> fix: signOut에 redirect 속성 추가

- .eslintrc.json
- public/custom-sw.js
- public/manifest.json
- public/offline.html
- src/middleware.ts
resolved: 
- 구글에서 제공하는 workbox를 서비스워커와 함께 사용
- pwabuilder로 apk를 받을 수 있도록 설정 추가
- 
- 
<br>
---
> service-worker workbox 적용

- .eslintrc.json
- public/custom-sw.js
- public/manifest.json
- public/offline.html
- src/app/(main)/login/auth/components/AuthLogin.tsx
- src/middleware.ts
> dev -> main 병합

- src/app/(main)/_components/atoms/CategoryAgora.tsx
- 카테고리 아고라 입장시 userId 설정해주지 않는 문제 해결
- 
<br>
---
> fix: 카테고리 아고라 입장시 userId 설정해주지 않는 문제 해결

- src/store/agora.ts
- userId를 받지 않았을 경우 default 값으로 0으로 설정
<br>
---
> fix : userId를 받지 않았을 경우 default 값으로 0으로 설정

- src/app/(main)/_components/atoms/CategoryAgora.tsx
- src/store/agora.ts
- 개발한 기능에 대한 간략한 설명을 적어주세요.
<br>
---
> Dev -> Main

- src/app/(main)/user-info/_component/molecules/ActionButtons.tsx
- src/app/(main)/user-info/_lib/deleteUserAccount.ts
> fix: Props 설정 변경

- public/manifest.json
- src/app/layout.tsx
- 매니페스트 테마 컬러 light/dark 모드에 따라 변경
- 
-
<br>
---
> manifest 테마 색상에 맞춰 color 값 변경

- README.md
> update : update demonstration video

- README.md
- src/app/(chat)/_components/molecules/AgoraUserList.tsx
- src/app/(chat)/_components/organisms/Header.tsx
- src/app/(main)/_components/molecules/AgoraListDecider.tsx
- src/app/(main)/user-info/_lib/deleteUserAccount.ts
- src/store/kick.ts
> feat : 강제퇴장 기능 구현 및 테스트

- src/app/(main)/_components/atoms/CategoryAgoraNowTitle.tsx
- src/app/(main)/_components/molecules/CategoryAgoraList.tsx
- src/app/(main)/_components/templates/SignIn.tsx
- src/app/(main)/_lib/postEnterAgoraInfo.ts
- []
- 활성화 아고라의 새로고침 버튼 동작하지 않는 버그 수정
- 토큰 만료시 입장하기 API 호출 후 `AUTH_MESSAGE Missing` 에러 발생 수정
- 아고라 정보를 불러오는 쿼리를 reset하여 다시 불러오도록 하였습니다.
- 인증 관련 메시지가 담겨있는 객체인 AUTH_MESSAGE를 import 하지 않아 발생한 문제로, import하여 해결하였습니다.
- 
<br>
---
> 홈 화면 버그 수정

- src/app/(chat)/_components/organisms/Header.tsx
- src/app/(chat)/utils/SocketErrorHandler.ts
- 배포시 발생한 에러 해결
- 리이슈 호출이 소켓 에러 핸들러에도 포함되어 소켓 에러 발생시 세션을 전달하는 것으로 수정하였습니다.
- 
- 
<br>
---
> 채팅방 소켓 인증 에러 확인을 위해 세션 전달

- README.md
- 개발한 기능에 대한 간략한 설명을 적어주세요.
<br>
---
> chore: 리드미 시연 영상 수정

- src/app/(chat)/utils/updateUserAccessMessage.tsx
- import문이 정상적으로 삽입되지 않은 문제를 해결했습니다.
<br>
---
> fix: import 에러 수정
